depgraph: fix visibility check for string-type symbols
Fix a TypeError caused by comparing
the new symbol value to the visibility dep value:

   TypeError: unorderable types: str() <= TristateKconfigSymbolValue()

This affected string symbols verbosely as excerpted above,
and int/hex symbols silently (potentially).
For these symbol types, the visilibity's boolean value is now used
("return visibility_value").